---
- name: Get Filebeat version
  ansible.builtin.include_tasks: install-get-version.yml
  when: not filebeat_version | default(false)

- name: Compile Filebeat MSI URL
  ansible.builtin.set_fact:
    filebeat_msi_download_url: "{{ filebeat_msi_download_url.replace('{{ filebeat_version }}', filebeat_version) }}"

- name: Debug Filebeat MSI URL
  ansible.builtin.debug:
    msg: "Filebeat MSI URL: {{ filebeat_msi_download_url }}"

- name: Check if Filebeat service exists
  ansible.windows.win_service_info:
    name: filebeat
  register: filebeat_service
  failed_when: false

- name: Install Filebeat on Windows
  ansible.windows.win_package:
    path: "{{ filebeat_msi_download_url }}"
    arguments: /qn /norestart
  when: filebeat_service.services | length == 0 or filebeat_reinstall or filebeat_upgrade
  notify: Restart Filebeat on Windows
