---
- name: Install Elasticsearch repository
  ansible.builtin.include_role:
    name: mmartinello.elastic
  vars:
    elastic_major_version: "{{ filebeat_major_version }}"

- name: Install Filebeat
  ansible.builtin.apt:
    name: filebeat
    state: present
  notify: Restart Filebeat
